//===----------------------------------------------------------------------===//
//                         Haybarn, powered by DuckDB
//
// duckdb/haybarn.h
//
// Build-identity macros. These are present only in the Haybarn engine's
// headers, never in upstream DuckDB, so downstream code (in-tree, extensions,
// and language bindings) can detect a Haybarn build at compile time.
//
// NOTE: keep this header pure-preprocessor and dependency-free so it stays
// valid in both C and C++ translation units. The C public header (duckdb.h)
// is autogenerated and inlines copies of these macros rather than including
// this file (to stay self-contained for C consumers) -- if you change the
// values here, also update src/include/duckdb/main/capi/header_generation/
// header_base.hpp.template and rerun scripts/generate_c_api.py.
//===----------------------------------------------------------------------===//

#pragma once

//! Presence flag. Use `#ifdef HAYBARN` to distinguish a Haybarn engine from
//! upstream DuckDB.
#define HAYBARN 1

//! Monotonic ABI/feature counter for Haybarn-specific, source-level
//! divergences from upstream. Bump by 1 whenever a change is introduced that
//! compiled consumers must branch on, then gate with:
//!   #if defined(HAYBARN) && HAYBARN_ABI_VERSION >= N
#define HAYBARN_ABI_VERSION 1
